### ISSUE TITLE
sollte da nicht "0" zugewiesen werden?

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/AlgoDat#61]
https://github.com/BackofenLab/AlgoDat/blob/5635eb3c8777e0b11ecc4e80c15dcde9a4699206/Lecture-4/Code/AssociativeArray.py#L10

**Comment by bgruening** [comment]
Wir könnten auch den Kommentar ändern :)

**Comment by martin-raden** [comment]
hehe, ne geht nicht, weil dann das ganze beispiel sinnlos ist (geht ums zählen...)

**Comment by martin-raden** [comment]
siehe [Seite 27](http://www.bioinf.uni-freiburg.de/Lehre/Courses/2017_WS/V_AuD/AlgoDatWS1718_Lecture_04.pdf)
