### ISSUE TITLE
[win7] build fail for Lecture 1, 11

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/AlgoDat#69]
Ich bekomm pdflatex errors (und damit build fails) fuer beide lectures. alle anderen bauen korrekt.

(Win7 + aktuelles MiKTeX)

```
make ALGO_DESIGN=ufcd ALGO_PROGLANG=python ALGO_LANGUAGE=eng
```

hier die logfiles

[Lecture-1.log](https://github.com/BackofenLab/AlgoDat/files/2558367/Lecture-1.log)
[Lecture-11.log](https://github.com/BackofenLab/AlgoDat/files/2558373/Lecture-11.log)

**Comment by martin-raden** [comment]
@TobiasFaller irgendeine Idee?

bei Lec-1 scheints ein color problem zu sein.. aber ich werd nicht schlau draus...

bei Lec-11 findet er scheinbar die bibliography nicht..

**Comment by TobiasFaller** [comment]
@martin-raden Lec-1 sollte mit #75 gefixt sein. Lec-11 funktioniert bei mir und auf dem Build-Server. Ich werde mir das also noch genauer ansehen müssen ...
