### ISSUE TITLE
title: "Data Structure" vs "Datastructure"

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/AlgoDat#72]
das letztere ist im Englischen Blödsinn..  und daher ein bissl peinlich auf der Startseite.. 

- [x] überall ändern
- [ ] slides neu bauen
- [ ] handout slides neu hochladen

@eggzilla @michauhl @TobiasFaller

**Comment by michauhl** [comment]
Ja das habe ich mir auch schon gedacht ..

**Comment by martin-raden** [comment]
na dann mal ran..
